name: PHP Composer

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

env:
  TEST_VARIABLE: "${{vars.ENV_TEST}}"

jobs:
  aws-rds-mysql:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Generate key
        run: php artisan key:generate

      - name: ssh aws ec2 connection
        run: ssh -i webServerTest.pem ubuntu@ec2-3-27-197-74.ap-southeast-2.compute.amazonaws.com

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Laravel Migrate Database
        run: php artisan migrate
      # - name: Execute tests (Unit and Feature tests) via PHPUnit
      #   run: vendor/bin/phpunit
